# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BricksUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bricks_user',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='SlideSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.IntegerField()),
                ('count', models.IntegerField()),
                ('remote_path', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[(0, 'Introduction'), (1, 'Presentation'), (2, 'Team Presentation'), (3, 'Conclusion')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bricks.BricksUser')),
            ],
            options={
                'db_table': 'slide_slice',
            },
        ),
        migrations.AddField(
            model_name='bricksuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bricks.Company'),
        ),
    ]
