# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.IntegerField()),
                ('count', models.IntegerField()),
                ('remote_path', models.CharField(max_length=255)),
                ('column', models.IntegerField()),
                ('checked', models.BooleanField()),
            ],
            options={
                'db_table': 'brick',
            },
        ),
        migrations.RemoveField(
            model_name='slideslice',
            name='user',
        ),
        migrations.DeleteModel(
            name='SlideSlice',
        ),
    ]
